# Copyright 2023 Andrew Symington
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# This is the offset of the marker position from the origin of the lighthouse.
# So, if you use an external system like a theodolite, precise RTK setup or
# motion capture system, this is the offset of its frame w.r.t the lighthouse.
#
# Looking directly at a lighthouse oriented upright, the coordinate frame is
# a conventional right-handed system with the following properties:
#
#   > +x points left.
#   > +y points up.
#   > +z points into the base station.
#
# In the example above the registration marker is 10cm above the lighthouse.
#
# NOTE: We force the id and channel to be redeclared in order to make sure
#       that the markers are for the configuration file and avoid mistakes.
#
# Note: All poses are expressed in the following order: [x,y,z,qw,qx,qy,qz]
#
lighthouse_from_marker:
  position: [0.0, 0.1, 0.0]   # 10cm "above" a base station
markers:
  lighthouse0:
    id: 384784632   # Serial number of lighthouse is LHR-hexidecimal(id)
    mode: 4         # This is the same as the channel
    position: [-0.000000000000, 1.458985931705, 10.020991301227]
    sigma: [0.001, 0.001, 0.001]
  lighthouse1:
    id: 2179997076  # Serial number of lighthouse is LHR-hexidecimal(id)
    mode: 2         # This is the same as the channel
    position: [1.351791827768, 2.519027929396, 10.408610236531]
    sigma: [0.001, 0.001, 0.001]
  lighthouse2:
    id: 1974130315   # Serial number of lighthouse is LHR-hexidecimal(id)
    mode: 1         # This is the same as the channel
    position: [1.780496197943, 2.585230340850, 10.484703390713]
    sigma: [0.001, 0.001, 0.001]
  lighthouse3:
    id: 1749379901 # Serial number of lighthouse is LHR-hexidecimal(id)
    mode: 0       # This is the same as the channel
    position: [3.024384244020, 2.637668639886, 10.302714251888]
    sigma: [0.001, 0.001, 0.001]
  lighthouse4:
    id: 3590859256 # Serial number of lighthouse is LHR-hexidecimal(id)
    mode: 3       # This is the same as the channel
    position: [0.779046606866, 2.678838980482, 10.948755064650]
    sigma: [0.001, 0.001, 0.001]
